apiVersion: v1
kind: Service
metadata:
  name: streetlight-api-service
spec:
  selector:
    app: streetlight-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
  type: LoadBalancer
